### ISSUE TITLE
hi, ict query

### ISSUE THREAD

**Issue by jun0wanan** [uvavision/Curriculum-Labeling#1]
hi, author:

   Thank you for your excellent code! I want to use your code to my baseline ,so can you help me how to use the ict model (second way to ssl)? hope to get your reply !

(●'◡'●)
Best，
jun0

**Comment by pcascanteb** [comment]
hi @jun0wanan, yes for sure, I  can add new code to use it with ICT and have it ready by next week, I'll keep you posted! 🙂

**Comment by jun0wanan** [comment]
> hi @jun0wanan, yes for sure, I can add new code to use it with ICT and have it ready by next week, I'll keep you posted! 🙂

oh,thank you very  much !!

**Comment by jun0wanan** [comment]
> hi @jun0wanan, yes for sure, I can add new code to use it with ICT and have it ready by next week, I'll keep you posted! 🙂

sorry, I am a newer (ssl)...   I think  the val dataset is different each epoch in your code .. Why you set that ? Or I didn't understand it .. ╥﹏╥...
![image](https://user-images.githubusercontent.com/54523624/113185727-63f35b80-9289-11eb-8dda-6a80c06c43d9.png)

**Comment by pcascanteb** [comment]
Hey @jun0wanan, that random.seed(seed) inside that for ensures to always get the same "random indexes"
You can check the documentation of that function here: https://docs.python.org/3/library/random.html or even test it by yourself!

check this code out:
```
seed = 0
for i in range (10):
        random.seed(seed)
        randomIndexes = random.sample(range(0, 10), 10)
        print (randomIndexes)
```

now try the same code but with the random.seed function outside the for
for multiple experiments, try different seeds, the distribution of the data change, but it's always the same in each iteration depending on the seed you chose 🙂

**Comment by jun0wanan** [comment]
> Hey @jun0wanan, that random.seed(seed) inside that for ensures to always get the same "random indexes"
> You can check the documentation of that function here: https://docs.python.org/3/library/random.html or even test it by yourself!
> 
> check this code out:
> 
> ```
> seed = 0
> for i in range (10):
>         random.seed(seed)
>         randomIndexes = random.sample(range(0, 10), 10)
>         print (randomIndexes)
> ```
> 
> now try the same code but with the random.seed function outside the for
> for multiple experiments, try different seeds, the distribution of the data change, but it's always the same in each iteration depending on the seed you chose 🙂

Thank you very much ! I have test it ,and you are right !

**Comment by jun0wanan** [comment]
> Hey @jun0wanan, that random.seed(seed) inside that for ensures to always get the same "random indexes"
> You can check the documentation of that function here: https://docs.python.org/3/library/random.html or even test it by yourself!
> 
> check this code out:
> 
> ```
> seed = 0
> for i in range (10):
>         random.seed(seed)
>         randomIndexes = random.sample(range(0, 10), 10)
>         print (randomIndexes)
> ```
> 
> now try the same code but with the random.seed function outside the for
> for multiple experiments, try different seeds, the distribution of the data change, but it's always the same in each iteration depending on the seed you chose 🙂

hi,
╥﹏╥... I want to trouble you again. I really want to ask you a question. I want to use SSL for other AI tasks than just sorting images. I was wondering if you think it would be feasible to add self-supervise methods to the pseudo-label method to make use of unlabeled data or improve the representation ? 
    Best wishes!

jun0 (●'◡'●)
