### ISSUE TITLE
The link about ZCA is invalid.

### ISSUE THREAD

**Issue by takiee** [uvavision/Curriculum-Labeling#3]
Hi~ I want to use your code,trying to duplicate the code, but the link about ZCA(http://cs.virginia.edu/~pcascante/zca_components.npy, http://cs.virginia.edu/~pcascante/zca_mean.npy) is valid. Could you please share the links again? I will be very grateful to you.

**Comment by pcascanteb** [comment]
Hi, I accidentally removed the files but I generated and put them back there -- let me know if you have any issue downloading them.

**Comment by zqs9810** [comment]
Could you please share the links again? I will be very grateful to you.
